name: goatsmart
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.5.0 # Update to the latest version
  firebase_auth: ^4.3.0 # Update to the latest version
  shared_preferences: ^2.0.6 # Update to the latest version
  flutter_form_builder: ^9.2.1 # Update to the latest version
  form_builder_validators: ^9.1.0 # Update to the latest version
  firebase_storage: ^11.6.9 # Update to the latest version
  get: ^4.3.8 # Update to the latest version
  cloud_firestore: ^4.15.8 # Update to the latest version
  intl_phone_number_input: ^0.7.4
  image_picker: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  assets:
    - assets/images/logo.png
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/4.jpg
    - assets/images/5.jpg
    - assets/images/6.jpg
    - assets/images/7.jpg
    - assets/images/8.jpg
    - assets/images/9.jpg
    - assets/images/10.jpg
    - assets/images/11.jpg
    - assets/images/12.jpg
    - assets/images/13.jpg
    - assets/images/14.jpg
    - assets/images/prof.jpg
    - assets/images/login_background.png
    - assets/images/registration_background.png
  uses-material-design: true
